package com.scbck.model;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.hibernate.validator.constraints.Length;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.scbck.json.DataUrlDeserializer;
import com.scbck.json.DataUrlSerializer;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Lob;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Size;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Past;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "employee")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Employee {

    /**
     * How a teacher is engaged, which decides how they are paid.
     *
     * Fixed lists rather than lookup tables: these are the categories the
     * Ministry recognises, not something the school invents, and a free-text
     * column produced "EPF", "epf" and "E.P.F." in the same register.
     */
    public static final java.util.List<String> APPOINTMENT_TYPES =
            java.util.List.of("Teacher service", "EPF", "Volunteer");

    /**
     * The qualification ladder, lowest rung first.
     *
     * Each rung includes the ones below it, which is how the school writes it
     * on its own staff return.
     */
    public static final java.util.List<String> EDUCATION_QUALIFICATIONS = java.util.List.of(
            "A/L",
            "A/L, Diploma",
            "A/L, Degree",
            "A/L, Degree, PGD",
            "A/L, Degree, MSc");

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Zero-padded staff number. Generated by the server on insert, so the client
     * never supplies it.
     */
    @Column(name = "emp_no", unique = true)
    @Length(max = 8)
    private String emp_no;

    @NotBlank(message = "is required")
    @Size(max = Validation.NAME_MAX, message = "is too long")
    @Pattern(regexp = Validation.PERSON_NAME, message = "may only contain letters, spaces, . ' and -")
    private String fullname;

    @Lob
    @Column(name = "emp_photo", columnDefinition = "LONGBLOB")
    @JsonSerialize(using = DataUrlSerializer.class)
    @JsonDeserialize(using = DataUrlDeserializer.class)
    private byte[] emp_photo;

    @NotBlank(message = "is required")
    @Size(max = Validation.NAME_MAX, message = "is too long")
    @Pattern(regexp = Validation.PERSON_NAME, message = "may only contain letters, spaces, . ' and -")
    private String callingname;

    @Column(name = "nic", unique = true)
    @NotBlank(message = "is required")
    @Pattern(regexp = Validation.NIC, message = "must be 9 digits and V, or 12 digits")
    private String nic;

    @NotBlank(message = "is required")
    @Size(max = 20, message = "is too long")
    private String gender;

    @NotNull(message = "is required")
    @Past(message = "must be in the past")
    private LocalDate dob;

    @Column(name = "email", unique = true)
    @Email(message = "must be a valid email address")
    @NotNull(message = "is required")
    private String email;

    @NotBlank(message = "is required")
    @Size(max = Validation.SHORT_TEXT_MAX, message = "is too long")
    private String civilstatus;

    @Length(max = 10, message = "must be at most 10 digits")
    @NotBlank(message = "is required")
    @Pattern(regexp = Validation.PHONE, message = "must be 10 digits starting with 0")
    private String mobileno;

    @Length(max = 10, message = "must be at most 10 digits")
    @Pattern(regexp = Validation.PHONE, message = "must be 10 digits starting with 0")
    private String landno;

    @NotBlank(message = "is required")
    @Size(max = Validation.ADDRESS_MAX, message = "is too long")
    private String address;

    @Size(max = Validation.NOTE_MAX, message = "is too long")
    private String note;

    /** Audit columns, populated server-side. */
    private LocalDateTime added_datetime;

    private LocalDateTime updated_datetime;

    private LocalDateTime deletd_datetime;

    private Integer added_user_id;

    private Integer updated_user_id;

    private Integer deleted_user_id;

    // ---- Teaching staff -----------------------------------------------------
    //
    // Only meaningful when the designation is Teacher. Kept on the employee
    // rather than in a table of their own because they are one-to-one with the
    // person and every one of them is a fact about the appointment, not an
    // event in it: a teacher has one appointment type, one appointment date and
    // one set of qualifications at a time. A separate table would buy nothing
    // and cost a join on every staff list.
    //
    // All nullable, because the non-teaching half of the staff has none of
    // them, and because the school is filling them in for existing records
    // rather than starting from a blank register.

    /** "Teacher service", "EPF" or "Volunteer". */
    @Column(name = "appointment_type", length = 40)
    @Size(max = 40, message = "is too long")
    private String appointmentType;

    @Column(name = "appointment_date")
    private LocalDate appointmentDate;

    /**
     * The date of retirement.
     *
     * Recorded ahead of time rather than on the day: the school plans staffing
     * against it, which is the point of holding it at all. It is therefore not
     * validated as being in the past.
     */
    @Column(name = "retired_date")
    private LocalDate retiredDate;

    /**
     * Up to three subjects the teacher would rather be timetabled for.
     *
     * Three columns rather than a link table for the same reason as above -
     * "preferred subject 1, 2, 3" is the school's own form, the order is the
     * preference, and a table would turn an ordered top-three into an unordered
     * set that has to be re-sorted everywhere it is read.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "preferred_subject_1_id", referencedColumnName = "id")
    private SubjectDetail preferredSubject1;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "preferred_subject_2_id", referencedColumnName = "id")
    private SubjectDetail preferredSubject2;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "preferred_subject_3_id", referencedColumnName = "id")
    private SubjectDetail preferredSubject3;

    /**
     * The highest qualification held, as one of the school's fixed rungs -
     * "A/L", "A/L, Diploma", "A/L, Degree", "A/L, Degree, PGD",
     * "A/L, Degree, MSc".
     *
     * A single ladder rather than a set of tick boxes because that is how the
     * school records it: each rung already includes the ones below it.
     */
    @Column(name = "education_qualification", length = 60)
    @Size(max = 60, message = "is too long")
    private String educationQualification;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "designation_id", referencedColumnName = "id")
    private Designation designation_id;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "status_id", referencedColumnName = "id")
    private Status status_id;
}
