package com.scbck.model;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.hibernate.validator.constraints.Length;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.scbck.json.DataUrlDeserializer;
import com.scbck.json.DataUrlSerializer;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Lob;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Size;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Past;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "employee")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Employee {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Zero-padded staff number. Generated by the server on insert, so the client
     * never supplies it.
     */
    @Column(name = "emp_no", unique = true)
    @Length(max = 8)
    private String emp_no;

    @NotBlank(message = "is required")
    @Size(max = Validation.NAME_MAX, message = "is too long")
    @Pattern(regexp = Validation.PERSON_NAME, message = "may only contain letters, spaces, . ' and -")
    private String fullname;

    @Lob
    @Column(name = "emp_photo", columnDefinition = "LONGBLOB")
    @JsonSerialize(using = DataUrlSerializer.class)
    @JsonDeserialize(using = DataUrlDeserializer.class)
    private byte[] emp_photo;

    @NotBlank(message = "is required")
    @Size(max = Validation.NAME_MAX, message = "is too long")
    @Pattern(regexp = Validation.PERSON_NAME, message = "may only contain letters, spaces, . ' and -")
    private String callingname;

    @Column(name = "nic", unique = true)
    @NotBlank(message = "is required")
    @Pattern(regexp = Validation.NIC, message = "must be 9 digits and V, or 12 digits")
    private String nic;

    @NotBlank(message = "is required")
    @Size(max = 20, message = "is too long")
    private String gender;

    @NotNull(message = "is required")
    @Past(message = "must be in the past")
    private LocalDate dob;

    @Column(name = "email", unique = true)
    @Email(message = "must be a valid email address")
    @NotNull(message = "is required")
    private String email;

    @NotBlank(message = "is required")
    @Size(max = Validation.SHORT_TEXT_MAX, message = "is too long")
    private String civilstatus;

    @Length(max = 10, message = "must be at most 10 digits")
    @NotBlank(message = "is required")
    @Pattern(regexp = Validation.PHONE, message = "must be 10 digits starting with 0")
    private String mobileno;

    @Length(max = 10, message = "must be at most 10 digits")
    @Pattern(regexp = Validation.PHONE, message = "must be 10 digits starting with 0")
    private String landno;

    @NotBlank(message = "is required")
    @Size(max = Validation.ADDRESS_MAX, message = "is too long")
    private String address;

    @Size(max = Validation.NOTE_MAX, message = "is too long")
    private String note;

    /** Audit columns, populated server-side. */
    private LocalDateTime added_datetime;

    private LocalDateTime updated_datetime;

    private LocalDateTime deletd_datetime;

    private Integer added_user_id;

    private Integer updated_user_id;

    private Integer deleted_user_id;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "designation_id", referencedColumnName = "id")
    private Designation designation_id;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "status_id", referencedColumnName = "id")
    private Status status_id;
}
