package com.scbck.model;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.hibernate.validator.constraints.Length;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.scbck.json.DataUrlDeserializer;
import com.scbck.json.DataUrlSerializer;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Lob;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "student")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Student {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Zero-padded admission number. Generated by the server on insert, so the
     * client never supplies it.
     */
    @Column(name = "stu_no", unique = true)
    @Length(max = 8)
    private String stu_no;

    @NotNull(message = "is required")
    private String fullname;

    @Lob
    @Column(name = "stu_photo", columnDefinition = "LONGBLOB")
    @JsonSerialize(using = DataUrlSerializer.class)
    @JsonDeserialize(using = DataUrlDeserializer.class)
    private byte[] stu_photo;

    @NotNull(message = "is required")
    private String callingname;

    @Column(name = "birth_certi_no", unique = true)
    @Length(min = 6, max = 12, message = "must be 6 to 12 characters")
    @NotNull(message = "is required")
    private String birth_certi_no;

    /** Optional: only older students hold an NIC. */
    @Column(name = "nic", unique = true)
    @Length(min = 10, max = 12, message = "must be 10 to 12 characters")
    private String nic;

    @NotNull(message = "is required")
    private String gender;

    @NotNull(message = "is required")
    private LocalDate dob;

    @NotNull(message = "is required")
    private String religion;

    @NotNull(message = "is required")
    private String nationality;

    @NotNull(message = "is required")
    private String previous_scl;

    @NotNull(message = "is required")
    private String address;

    private String note;

    /** Audit columns, populated server-side. */
    private LocalDateTime added_datetime;

    private LocalDateTime updated_datetime;

    private LocalDateTime deleted_datetime;

    private Integer added_user_id;

    private Integer updated_user_id;

    private Integer deleted_user_id;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "student_status_id", referencedColumnName = "id")
    private StudentStatus student_status_id;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "grade_id", referencedColumnName = "id")
    private Grade grade_id;

    /**
     * The guardian this student is registered under. Present in the ER model but
     * previously missing from the entity, which made the relationship
     * impossible to persist.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "guardian_id", referencedColumnName = "id")
    private Guardian guardian_id;
}
